# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

HOME = '/home/vagrant'

Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"

  config.vm.box_check_update = true
  config.vm.define 'cooper-dev-box'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path ['../../chef_cookbooks']
    chef.add_recipe 'git'
    chef.add_recipe 'mongodb-org-3'
    chef.add_recipe 'rbenv-2.3.0'
    chef.add_recipe 'vim'
  end

  config.vm.provision 'shell', inline: "rm -rf #{HOME}/.vim"
  config.vm.provision 'file', source: '~/.vim/', destination: '.vim/'
  config.vm.provision 'file', source: '~/.vimrc', destination: '.vimrc'

  config.vm.provision 'file', source: '~/.ssh/id_rsa.pub', destination: "#{HOME}/.ssh/id_rsa.pub"
  config.vm.provision 'file', source: '~/.ssh/id_rsa', destination: "#{HOME}/.ssh/id_rsa"
end
